image: iceyec/ci-rust

build:
  before_script:
    # some native deps
    - sudo apt-get -y install software-properties-common python-software-properties
    - sudo add-apt-repository ppa:git-core/ppa
    - sudo apt-get update
    - sudo apt-get -y install cmake libXxf86vm-dev libxinerama-dev libxcursor-dev git xorg-dev
    # glfw
    - git clone https://github.com/glfw/glfw.git
    - cd glfw
    - git checkout 3.0.3
    - sudo apt-get -y build-dep glfw
    - cmake -DBUILD_SHARED_LIBS=ON
    - make
    - sudo make install
    - cd ..
    - export LD_LIBRARY_PATH=/usr/local/lib
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo
    - cargo build --release --verbose
