image: iceyec/ci-rust

build:
  before_script:
    - git clone https://github.com/glfw/glfw.git
    - cd glfw
    - git checkout 3.0.3
    - cmake -DBUILD_SHARED_LIBS=ON
    - make
    - sudo make install
  script:
    - curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y --disable-sudo
    - cargo build --release --verbose
